[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[variables]
PYTHONUNBUFFERED = "1"
ENVIRONMENT = "production"
DEBUG = "false"
LOG_LEVEL = "info"