[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
PYTHONUNBUFFERED = "1"
ENVIRONMENT = "production"
DEBUG = "false"
LOG_LEVEL = "info"